### ISSUE TITLE
Šablona pro XSS

### ISSUE THREAD

**Issue by iBobik** [spaze/webtop100#1]
Máš nějakou ukázku textu, co můžeme sázet do formulářových polí, abychom otestovali XSS při zobrazení administrace? Mělo by se to pokusit vyvolat HTTP request na náš skript, případně k tomu i vycucnout cookies přes JS.

Můžeme vyjít z těchto příkladů?
https://www.owasp.org/index.php/Cross-site_Scripting_%28XSS%29

**Comment by iBobik** [comment]
K tomu skriptu, který zaloguje request: Je v pohodě to mít na své doméně, nebo bychom z toho mohli mít nějaké nepříjemnosti? Existuje nějaká hotová anonymní alternativa?

**Comment by spaze** [comment]
Stačí zjistit, že se _neescapují_ znaky `<`, `>`, `"`,`'` a třeba zobrazit nějaký _alert_. Útok _session hijacking_ není součástí hodnocení, ostatně součástí vlastně není ani XSS. Hledáme technické chyby, které k takovému útoku mohou vést, neútočíme.

**Comment by iBobik** [comment]
Je tam formulář pro HR, jehož výsledek se nerenderuje tomu, kdo jej vyplní, ale může se renderovat v nějaké administraci, takže jsem chtěl vyzkoušet stored xss, jinak nejsem schopný ten formulář na xss otestovat.

Jan Pobořil
http://honza.poboril.cz/

05 Jul 2015 v 20:17, Michal Špaček <notifications@github.com>:
